### ISSUE TITLE
Retrying of connection

### ISSUE THREAD

**Issue by jonathanleinola** [OmronAPAC/Omron_AMR_ROS2#4]
Hi, 
how could I retry the connection made by arcl_api_server.py?
Sometimes it drops out the connection.

Kindly,
Jonathan

**Comment by CFZeon** [comment]
Hi Jonathan,

If the ARCL server stops responding it occasionally happens because it receives a message that it is not made to handle. Messages like these include common ones like Stopped, undocking failed, failed to reach goal and other errors. See the implementation of the parser class here: https://github.com/OmronAPAC/Omron_AMR_ROS2/blob/master/src/om_aiv_navigation/om_aiv_navigation/action_server.py on how to handle outlier messages that the AMR might send.

Regards,
Zeon

**Comment by jonathanleinola** [comment]
Hey,

the same happens if i connect by using telnet to the robot. The omron robot "kicks out" the telnet client, same happens with arcl server.

-Jonathan

**Comment by CFZeon** [comment]
Hi Jonathan,

From my experience, the robot works completely fine when you open multiple telnet connections but my computer is often connected via LAN instead of WLAN. It could be a network error on your end but I will get back to you on this behaviour if I come across anything.

Regards,
Zeon

**Comment by jrajaram20** [comment]
closing non-active issues
